const { existingIds } = require('./pridej-diagnozy.cjs');
const KAT_MR    = 'F70–F79 Mentální retardace';
const KAT_VYVOJ = 'F80–F89 Poruchy psychického vývoje';
const KAT_DET   = 'F90–F98 Poruchy chování s počátkem v dětství a dospívání';

// Helper: creates F7x.0/.1/.8/.9 behavior specifiers for mental retardation
function mrSubcodes(prefix, nazev, uroven, mapMkn11, mapDsm5) {
  return [
    { s:'.0', n:`${nazev} – bez poruch chování nebo s minimálními poruchami chování`,
      p:`${uroven} intelektuální porucha bez výrazných poruch chování.`,
      k:[`IQ odpovídá ${uroven.toLowerCase()} retardaci`,`Bez výrazné poruchy chování`],
      z:['intelektuální omezení','omezení adaptivního chování'],
      pr:'Trvalý.', on:'Kongenitální nebo v raném dětství.', dsm: mapDsm5+'.01' },
    { s:'.1', n:`${nazev} – s výraznou poruchou chování vyžadující léčbu nebo péči`,
      p:`${uroven} intelektuální porucha s výraznou poruchou chování (agresivita, sebepoškozování, stereotypní chování) vyžadující specifickou léčbu.`,
      k:[`IQ odpovídá ${uroven.toLowerCase()} retardaci`,`Výrazná porucha chování`,`Vyžaduje specifické terapeutické opatření`],
      z:['agresivita','sebepoškozování','stereotypní chování','záchvaty vzteku','poruchy pozornosti'],
      pr:'Trvalý.', on:'Kongenitální nebo v raném dětství.', dsm: mapDsm5+'.11' },
    { s:'.8', n:`${nazev} – s jinou poruchou chování`,
      p:`${uroven} intelektuální porucha s jinou poruchou chování než výše uvedenou.`,
      k:[`IQ odpovídá ${uroven.toLowerCase()} retardaci`,`Přítomna jiná porucha chování`],
      z:['variabilní poruchy chování','stereotypní pohyby','impulsivita'],
      pr:'Trvalý.', on:'Kongenitální nebo v raném dětství.', dsm: mapDsm5+'.81' },
    { s:'.9', n:`${nazev} – bez informace o poruše chování`,
      p:`${uroven} intelektuální porucha, informace o poruchách chování nejsou k dispozici.`,
      k:[`IQ odpovídá ${uroven.toLowerCase()} retardaci`,`Chybí informace o chování`],
      z:['intelektuální omezení'],
      pr:'Trvalý.', on:'Kongenitální nebo v raném dětství.', dsm: mapDsm5+'.91' },
  ].map(s => ({
    id: `${prefix}${s.s}`, kod: `${prefix}${s.s}`,
    nazev_cz: s.n, system: 'MKN-10',
    kategorie: KAT_MR, podkategorie: nazev,
    popis: s.p, diagnosticka_kriteria: s.k,
    priznaky: s.z, prubeh: s.pr, onset: s.on,
    diferencialni_diagnozy: [],
    mapovani: { mkn11: mapMkn11, dsm5: s.dsm }
  }));
}

const nove = [
  // F70–F79 mental retardation subcodes
  ...mrSubcodes('F70','Lehká mentální retardace','Lehká','6A00.0','317'),
  ...mrSubcodes('F71','Středně těžká mentální retardace','Středně těžká','6A00.1','318.0'),
  ...mrSubcodes('F72','Těžká mentální retardace','Těžká','6A00.2','318.1'),
  ...mrSubcodes('F73','Hluboká mentální retardace','Hluboká','6A00.3','318.2'),
  ...mrSubcodes('F78','Jiná mentální retardace','Jiná','6A00.Z','319'),
  ...mrSubcodes('F79','Neurčená mentální retardace','Neurčená',null,'319'),

  // F80 – speech/language development
  { id:'F80.3', kod:'F80.3', nazev_cz:'Získaná afázie s epilepsií (Landau-Kleffnerův syndrom)',
    system:'MKN-10', kategorie:KAT_VYVOJ, podkategorie:'Specifické vývojové poruchy řeči a jazyka',
    popis:'Porucha, při níž dítě po normálním vývoji ztrácí receptivní i expresivní jazykové schopnosti, spojená s epileptiformní EEG aktivitou.',
    diagnosticka_kriteria:['Normální jazykový vývoj před počátkem poruchy','Ztráta receptivní i expresivní řeči','Epileptiformní EEG aktivita','Věk počátku 3–9 let'],
    priznaky:['ztráta řeči po normálním vývoji','agnozia pro zvuky','epileptické záchvaty','poruchy chování'],
    prubeh:'Variabilní, může dojít k částečné obnově.', onset:'3–9 let.',
    diferencialni_diagnozy:['F84.0','F80.1','F80.2'], mapovani:{mkn11:'6A01.3',dsm5:null} },

  { id:'F80.8', kod:'F80.8', nazev_cz:'Jiné vývojové poruchy řeči a jazyka', system:'MKN-10',
    kategorie:KAT_VYVOJ, podkategorie:'Specifické vývojové poruchy řeči a jazyka',
    popis:'Jiné specifické vývojové poruchy řeči a jazyka nespadající do F80.0–F80.3.',
    diagnosticka_kriteria:['Vývojová porucha řeči nebo jazyka','Nespadá do F80.0–F80.3'],
    priznaky:['poruchy řeči nebo jazyka'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F80.0','F80.1','F80.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F80.9', kod:'F80.9', nazev_cz:'Vývojová porucha řeči a jazyka NS', system:'MKN-10',
    kategorie:KAT_VYVOJ, podkategorie:'Specifické vývojové poruchy řeči a jazyka',
    popis:'Neurčená vývojová porucha řeči a jazyka.',
    diagnosticka_kriteria:['Vývojová porucha řeči nebo jazyka','Nelze upřesnit typ'],
    priznaky:['poruchy řeči nebo jazyka'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F80.0','F80.1'], mapovani:{mkn11:null,dsm5:null} },

  // F81
  { id:'F81.3', kod:'F81.3', nazev_cz:'Smíšená vývojová porucha školních dovedností', system:'MKN-10',
    kategorie:KAT_VYVOJ, podkategorie:'Specifické vývojové poruchy školních dovedností',
    popis:'Kombinace poruch čtení, pravopisu i matematiky.',
    diagnosticka_kriteria:['Kombinace výrazných poruch čtení, pravopisu a matematiky','Nespadá do jedné ze specifických kategorií'],
    priznaky:['poruchy čtení','poruchy pravopisu','poruchy matematiky','frustrace ze školní práce'],
    prubeh:'Chronický.', onset:'Začátek školní docházky.',
    diferencialni_diagnozy:['F81.0','F81.1','F81.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F81.8', kod:'F81.8', nazev_cz:'Jiné vývojové poruchy školních dovedností', system:'MKN-10',
    kategorie:KAT_VYVOJ, podkategorie:'Specifické vývojové poruchy školních dovedností',
    popis:'Jiné specifické vývojové poruchy školních dovedností nespadající do F81.0–F81.3.',
    diagnosticka_kriteria:['Vývojová porucha školních dovedností','Nespadá do F81.0–F81.3'],
    priznaky:['poruchy školních dovedností'],
    prubeh:'Chronický.', onset:'Dětství.',
    diferencialni_diagnozy:['F81.0','F81.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F81.9', kod:'F81.9', nazev_cz:'Vývojová porucha školních dovedností NS', system:'MKN-10',
    kategorie:KAT_VYVOJ, podkategorie:'Specifické vývojové poruchy školních dovedností',
    popis:'Neurčená vývojová porucha školních dovedností.',
    diagnosticka_kriteria:['Vývojová porucha školních dovedností','Nelze upřesnit typ'],
    priznaky:['poruchy školních dovedností'],
    prubeh:'Chronický.', onset:'Dětství.',
    diferencialni_diagnozy:['F81.0'], mapovani:{mkn11:null,dsm5:null} },

  // F84
  { id:'F84.4', kod:'F84.4', nazev_cz:'Hyperaktivní porucha spojená s mentální retardací a stereotypními pohyby',
    system:'MKN-10', kategorie:KAT_VYVOJ, podkategorie:'Pervazivní vývojové poruchy',
    popis:'Špatně definovaná porucha nejisté nozologické validity kombinující hyperaktivitu, stereotypní pohyby a mentální retardaci. Nevhodná odpověď na stimulancia (časté zhoršení).',
    diagnosticka_kriteria:['Výrazná hyperaktivita','Stereotypní pohyby','Mentální retardace (IQ pod 50)','Nevhodná reakce na stimulancia'],
    priznaky:['hyperaktivita','stereotypní pohyby','mentální retardace','impulzivita','sebepoškozování'],
    prubeh:'Chronický.', onset:'Raná adolescence – hyperaktivita může ustupovat.',
    diferencialni_diagnozy:['F90.0','F84.0','F70'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F84.8', kod:'F84.8', nazev_cz:'Jiné pervazivní vývojové poruchy', system:'MKN-10',
    kategorie:KAT_VYVOJ, podkategorie:'Pervazivní vývojové poruchy',
    popis:'Jiné pervazivní vývojové poruchy nespadající do F84.0–F84.5.',
    diagnosticka_kriteria:['Pervazivní vývojová porucha','Nespadá do F84.0–F84.5'],
    priznaky:['poruchy sociálního vývoje','komunikační deficity','repetitivní chování'],
    prubeh:'Chronický.', onset:'Raná adolescence.',
    diferencialni_diagnozy:['F84.0','F84.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F84.9', kod:'F84.9', nazev_cz:'Pervazivní vývojová porucha NS', system:'MKN-10',
    kategorie:KAT_VYVOJ, podkategorie:'Pervazivní vývojové poruchy',
    popis:'Neurčená pervazivní vývojová porucha.',
    diagnosticka_kriteria:['Pervazivní vývojová porucha','Nelze upřesnit typ'],
    priznaky:['poruchy sociálního vývoje a komunikace'],
    prubeh:'Chronický.', onset:'Raná adolescence.',
    diferencialni_diagnozy:['F84.0'], mapovani:{mkn11:null,dsm5:'299.80'} },

  // F90
  { id:'F90.8', kod:'F90.8', nazev_cz:'Jiné hyperkinetické poruchy', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Hyperkinetické poruchy',
    popis:'Hyperkinetické poruchy nespadající do F90.0 nebo F90.1.',
    diagnosticka_kriteria:['Hyperaktivita a nepozornost','Nespadá do F90.0 nebo F90.1'],
    priznaky:['hyperaktivita','nepozornost','impulzivita'],
    prubeh:'Chronický.', onset:'Dětství.',
    diferencialni_diagnozy:['F90.0','F90.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F90.9', kod:'F90.9', nazev_cz:'Hyperkinetická porucha NS', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Hyperkinetické poruchy',
    popis:'Neurčená hyperkinetická porucha.',
    diagnosticka_kriteria:['Hyperkinetická porucha','Nelze upřesnit typ'],
    priznaky:['hyperaktivita','nepozornost'],
    prubeh:'Chronický.', onset:'Dětství.',
    diferencialni_diagnozy:['F90.0','F90.1'], mapovani:{mkn11:null,dsm5:'314.01'} },

  // F91
  { id:'F91.0', kod:'F91.0', nazev_cz:'Porucha chování vázaná na vztah k rodině', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy chování',
    popis:'Dissociální nebo agresivní chování omezené výhradně nebo téměř výhradně na domácí prostředí a interakce s rodinnými příslušníky.',
    diagnosticka_kriteria:['Porucha chování splňující obecná kritéria F91','Chování se projevuje výhradně doma nebo ve vztahu k rodině','Dobré fungování mimo rodinu'],
    priznaky:['krádež doma','agresivita vůči rodinným příslušníkům','ničení rodinného majetku','opozičnost doma'],
    prubeh:'Může odeznít s věkem nebo při změně rodinných podmínek.', onset:'Dětství.',
    diferencialni_diagnozy:['F91.1','F91.2','F93'], mapovani:{mkn11:'6C91.0',dsm5:'313.81'} },

  { id:'F91.1', kod:'F91.1', nazev_cz:'Nesocializovaná porucha chování', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy chování',
    popis:'Přetrvávající dissociální nebo agresivní chování bez integrace do skupiny vrstevníků. Dítě nemá nebo neudržuje přátelství.',
    diagnosticka_kriteria:['Obecná kritéria poruchy chování F91','Chybí integrace do skupiny vrstevníků','Absence blízkých přátelství','Odmítání nebo odmítnutí vrstevníky'],
    priznaky:['agresivita','krutost vůči lidem nebo zvířatům','krádež','odmítnutí vrstevníky','sociální izolace','lhaní'],
    prubeh:'Horší prognóza než F91.2. Může přejít v poruchu osobnosti.', onset:'Dětství.',
    diferencialni_diagnozy:['F91.2','F91.3','F60.2'], mapovani:{mkn11:'6C91.1',dsm5:'312.81'} },

  { id:'F91.2', kod:'F91.2', nazev_cz:'Socializovaná porucha chování', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy chování',
    popis:'Přetrvávající dissociální nebo agresivní chování u dětí, která jsou dobře integrována do skupiny vrstevníků (delikventní skupiny).',
    diagnosticka_kriteria:['Obecná kritéria poruchy chování F91','Dobré vztahy s vrstevníky (byť v delikventní skupině)','Dissociální chování skupinového charakteru'],
    priznaky:['krádeže ve skupině','ničení majetku','agresivita mimo rodinu','skupinové delikvence','záškoláctví'],
    prubeh:'Lepší prognóza než F91.1. Může odeznít.', onset:'Dětství nebo adolescence.',
    diferencialni_diagnozy:['F91.1','F91.0','F91.3'], mapovani:{mkn11:'6C91.2',dsm5:'312.82'} },

  { id:'F91.8', kod:'F91.8', nazev_cz:'Jiné poruchy chování', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy chování',
    popis:'Jiné poruchy chování nespadající do F91.0–F91.3.',
    diagnosticka_kriteria:['Porucha chování','Nespadá do F91.0–F91.3'],
    priznaky:['dissociální nebo agresivní chování','variabilní'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F91.0','F91.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F91.9', kod:'F91.9', nazev_cz:'Porucha chování NS', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy chování',
    popis:'Neurčená porucha chování.',
    diagnosticka_kriteria:['Porucha chování','Nelze upřesnit typ'],
    priznaky:['dissociální nebo agresivní chování'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F91.1','F91.2'], mapovani:{mkn11:null,dsm5:'312.9'} },

  // F93
  { id:'F93.2', kod:'F93.2', nazev_cz:'Sociální úzkostná porucha v dětství', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Emocionální poruchy s počátkem v dětství',
    popis:'Přetrvávající výrazná úzkost v sociálních situacích s cizími lidmi (dospělými nebo vrstevníky), při zachované normální vazby k rodičům.',
    diagnosticka_kriteria:['Výrazná a přetrvávající úzkost v sociálních situacích s cizími','Normální vazba k rodičům a blízkým','Věk onset do 6 let','Způsobuje funkční omezení'],
    priznaky:['výrazná plachost v cizím prostředí','vyhýbání se cizím lidem','úzkost v nových situacích','normální sociální fungování s blízkými'],
    prubeh:'Může odeznít s věkem.', onset:'Dětství (do 6 let).',
    diferencialni_diagnozy:['F40.1','F93.0','F93.1'], mapovani:{mkn11:'6B04',dsm5:'300.23'} },

  { id:'F93.3', kod:'F93.3', nazev_cz:'Porucha sourozenecké rivality', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Emocionální poruchy s počátkem v dětství',
    popis:'Výrazné emocionální poruchy po narození mladšího sourozence projevující se negativismem, záchvaty vzteku nebo regresí (pomočování).',
    diagnosticka_kriteria:['Začátek po narození mladšího sourozence','Výrazná a přetrvávající emocionální porucha','Projevy: negativismus, regrese, žárlivost'],
    priznaky:['žárlivost na sourozence','regrese (pomočování)','záchvaty vzteku','žádání nadměrné pozornosti','agresivita vůči sourozenci'],
    prubeh:'Přechodný, obvykle odeznívá.', onset:'Po narození sourozence.',
    diferencialni_diagnozy:['F93.0','F93.1','normální žárlivost'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F93.8', kod:'F93.8', nazev_cz:'Jiné emocionální poruchy s počátkem v dětství', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Emocionální poruchy s počátkem v dětství',
    popis:'Jiné emocionální poruchy s počátkem v dětství nespadající do F93.0–F93.3.',
    diagnosticka_kriteria:['Emocionální porucha s počátkem v dětství','Nespadá do F93.0–F93.3'],
    priznaky:['emocionální poruchy','úzkost','strach'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F93.0','F93.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F93.9', kod:'F93.9', nazev_cz:'Emocionální porucha s počátkem v dětství NS', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Emocionální poruchy s počátkem v dětství',
    popis:'Neurčená emocionální porucha s počátkem v dětství.',
    diagnosticka_kriteria:['Emocionální porucha s počátkem v dětství','Nelze upřesnit typ'],
    priznaky:['emocionální poruchy v dětství'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F93.0','F93.1'], mapovani:{mkn11:null,dsm5:null} },

  // F94
  { id:'F94.1', kod:'F94.1', nazev_cz:'Reaktivní porucha příchylnosti v dětství', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy sociálního fungování s počátkem v dětství',
    popis:'Trvale abnormální vzorec navazování vztahů s výraznou inhibicí, hypervigilancí, strachem a smutkem. Závisí na patogenní péči v raném dětství.',
    diagnosticka_kriteria:['Abnormální vzorec vztahů s pečovateli','Inhibice, hypervigilance nebo dezorganizace vazby','Patogenní péče v anamnéze (zanedbávání, zneužívání)','Začátek do 5 let'],
    priznaky:['inhibice','hypervigilance','strach a smutek','ambivalentní chování k pečovatelům','potíže s uklidněním'],
    prubeh:'Zlepšuje se s adekvátní péčí.', onset:'Raná adolescence (do 5 let).',
    diferencialni_diagnozy:['F94.2','F84.0','F93.0'], mapovani:{mkn11:'6B44',dsm5:'313.89'} },

  { id:'F94.2', kod:'F94.2', nazev_cz:'Dezinhibiční porucha příchylnosti v dětství', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy sociálního fungování s počátkem v dětství',
    popis:'Difuzní, nediferencované chování navazování vztahů bez výběru – dítě se váže na kohokoliv, bez odlišení blízkých od cizích.',
    diagnosticka_kriteria:['Difuzní navazování vztahů bez výběru','Bez specifické vazby k pečovatelům','Patogenní péče v anamnéze','Začátek do 5 let'],
    priznaky:['chování „lepkavého" dítěte','bez selektivní vazby','nediferencovaná přívětivost','vyžadování pozornosti od cizích'],
    prubeh:'Výraznější než F94.1 tendence přetrvávat.', onset:'Raná adolescence.',
    diferencialni_diagnozy:['F94.1','F84.0','F90.0'], mapovani:{mkn11:'6B45',dsm5:'313.89'} },

  { id:'F94.8', kod:'F94.8', nazev_cz:'Jiné poruchy sociálního fungování s počátkem v dětství', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy sociálního fungování s počátkem v dětství',
    popis:'Jiné poruchy sociálního fungování s počátkem v dětství.',
    diagnosticka_kriteria:['Porucha sociálního fungování s počátkem v dětství','Nespadá do F94.0–F94.2'],
    priznaky:['poruchy sociálního fungování'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F94.1','F94.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F94.9', kod:'F94.9', nazev_cz:'Porucha sociálního fungování s počátkem v dětství NS', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Poruchy sociálního fungování s počátkem v dětství',
    popis:'Neurčená porucha sociálního fungování s počátkem v dětství.',
    diagnosticka_kriteria:['Porucha sociálního fungování','Nelze upřesnit typ'],
    priznaky:['poruchy sociálního fungování'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F94.1'], mapovani:{mkn11:null,dsm5:null} },

  // F95
  { id:'F95.0', kod:'F95.0', nazev_cz:'Přechodná tiková porucha', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Tikové poruchy',
    popis:'Tiky jednoho nebo více typů přetrvávající méně než 12 měsíců. Nejčastější forma tikové poruchy u dětí.',
    diagnosticka_kriteria:['Jeden nebo více typů tiků','Trvání méně než 12 měsíců','Věk počátku do 18 let'],
    priznaky:['motorické tiky (mrkání, grimasy)','vokální tiky','přechodný průběh'],
    prubeh:'Přechodný, do 12 měsíců.', onset:'Dětství, 4–8 let.',
    diferencialni_diagnozy:['F95.1','F95.2'], mapovani:{mkn11:'8A05',dsm5:'307.21'} },

  { id:'F95.1', kod:'F95.1', nazev_cz:'Chronická motorická nebo vokální tiková porucha', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Tikové poruchy',
    popis:'Motorické nebo vokální tiky (nikoli obojí), trvající déle než 12 měsíců.',
    diagnosticka_kriteria:['Buď motorické, nebo vokální tiky (nikoli obojí)','Trvání déle než 12 měsíců','Věk počátku do 18 let','Tiky nejsou způsobeny látkami nebo organicky'],
    priznaky:['chronické motorické tiky (mrkání, třepetání hlavou)','nebo chronické vokální tiky','tiky se mohou měnit v čase'],
    prubeh:'Chronický, více než 12 měsíců.', onset:'Dětství.',
    diferencialni_diagnozy:['F95.0','F95.2'], mapovani:{mkn11:'8A05',dsm5:'307.22'} },

  { id:'F95.8', kod:'F95.8', nazev_cz:'Jiné tikové poruchy', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Tikové poruchy',
    popis:'Jiné tikové poruchy nespadající do F95.0–F95.2.',
    diagnosticka_kriteria:['Tikové příznaky','Nespadají do F95.0–F95.2'],
    priznaky:['tiky','variabilní klinický obraz'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F95.0','F95.1','F95.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F95.9', kod:'F95.9', nazev_cz:'Tiková porucha NS', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Tikové poruchy',
    popis:'Neurčená tiková porucha.',
    diagnosticka_kriteria:['Tiková porucha','Nelze upřesnit typ'],
    priznaky:['tiky'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F95.0','F95.1'], mapovani:{mkn11:null,dsm5:'307.20'} },

  // F98
  { id:'F98.2', kod:'F98.2', nazev_cz:'Poruchy příjmu potravy v kojeneckém věku a v dětství', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Jiné poruchy chování s počátkem v dětství',
    popis:'Různorodé poruchy příjmu potravy v dětství nezpůsobené organicky: odmítání jídla, výběrovost, přejídání. Odlišit od F50.',
    diagnosticka_kriteria:['Věk počátku před 6 lety','Odmítání jídla, výběrovost nebo regurgitace','Bez organické příčiny','Nezapadá do F50'],
    priznaky:['odmítání jídla','výběrovost','regurgitace','neprospívání','podrážděnost při jídle'],
    prubeh:'Přechodný, zlepšuje se s věkem.', onset:'Kojenecký nebo předškolní věk.',
    diferencialni_diagnozy:['F50.0','organická onemocnění'], mapovani:{mkn11:'6B84',dsm5:'307.59'} },

  { id:'F98.3', kod:'F98.3', nazev_cz:'Pika v kojeneckém věku a v dětství', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Jiné poruchy chování s počátkem v dětství',
    popis:'Přetrvávající pojídání nejedlých látek (hlína, písek, barvy, tkaniny). Způsobuje zdravotní rizika.',
    diagnosticka_kriteria:['Přetrvávající pojídání nepotravinových látek','Věk alespoň 2 roky','Trvání nejméně 1 měsíc','Není součástí jiné duševní poruchy'],
    priznaky:['pojídání hlíny','pojídání písku nebo barvy','zdravotní komplikace (otrava olovem, střevní obstrukce)','nutritivní deficit'],
    prubeh:'Přechodný u dětí, může přetrvávat u mentálně retardovaných.', onset:'2–6 let.',
    diferencialni_diagnozy:['F70','F84.0'], mapovani:{mkn11:'6B84',dsm5:'307.52'} },

  { id:'F98.4', kod:'F98.4', nazev_cz:'Stereotypní pohybové poruchy', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Jiné poruchy chování s počátkem v dětství',
    popis:'Záměrné, opakované, stereotypní nepurpozivní pohyby (kývání těla, třepání rukami, bouchání hlavou) způsobující sebepoškozování nebo interferující s normálními aktivitami.',
    diagnosticka_kriteria:['Dobrovolné, stereotypní, opakující se pohyby','Nejde o tic ani kompulzi','Způsobují sebepoškozování nebo interferují s aktivitami','Trvání nejméně 4 týdny'],
    priznaky:['kývání těla','třepání rukama','bouchání hlavou','mávání','sebepoškozování'],
    prubeh:'Chronický.', onset:'Dětství.',
    diferencialni_diagnozy:['F84.0','F95.0','F42','organické poruchy'], mapovani:{mkn11:'8A05',dsm5:'307.3'} },

  { id:'F98.5', kod:'F98.5', nazev_cz:'Koktavost', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Jiné poruchy chování s počátkem v dětství',
    popis:'Porucha plynulosti řeči charakterizovaná opakováním nebo prodlužováním zvuků, slabik nebo slov, nebo přestávkami a zámlkami narušujícími rytmický tok řeči.',
    diagnosticka_kriteria:['Opakování nebo prodlužování zvuků a slabik','Poruchy plynulosti řeči','Způsobuje distres nebo omezení komunikace','Není způsobena organicky'],
    priznaky:['opakování slabik','prodlužování zvuků','tiché pauzy','viditelná napětí při řeči','vyhýbání se mluvení','sekundární pohyby'],
    prubeh:'Může přetrvávat nebo spontánně odeznít.', onset:'2–7 let.',
    diferencialni_diagnozy:['F98.6','F80.0','organická dysartrie'], mapovani:{mkn11:'6A01.4',dsm5:'307.0'} },

  { id:'F98.6', kod:'F98.6', nazev_cz:'Breptavost', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Jiné poruchy chování s počátkem v dětství',
    popis:'Vysoké tempo řeči s narušením plynulosti bez opakování, charakteristické pro breptavost (cluttering). Řeč je nesrozumitelná z důvodu rychlosti.',
    diagnosticka_kriteria:['Vysoké tempo řeči','Narušení plynulosti bez opakování','Srozumitelnost snížena','Není způsobena organicky'],
    priznaky:['vysoké tempo řeči','zkracování slov','nesprávné pauzy','nízká sebereflexe ohledně problému','špatná srozumitelnost'],
    prubeh:'Chronický.', onset:'Dětství.',
    diferencialni_diagnozy:['F98.5','F80.0'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F98.8', kod:'F98.8', nazev_cz:'Jiné určené poruchy chování s počátkem v dětství a dospívání', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Jiné poruchy chování s počátkem v dětství',
    popis:'Jiné určené poruchy chování s počátkem v dětství nespadající do jiných kategorií.',
    diagnosticka_kriteria:['Porucha chování s počátkem v dětství','Nelze klasifikovat jinde'],
    priznaky:['variabilní poruchy chování'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F98.0','F98.4'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F98.9', kod:'F98.9', nazev_cz:'Neurčená porucha chování s počátkem v dětství a dospívání', system:'MKN-10',
    kategorie:KAT_DET, podkategorie:'Jiné poruchy chování s počátkem v dětství',
    popis:'Neurčená porucha chování s počátkem v dětství.',
    diagnosticka_kriteria:['Porucha chování s počátkem v dětství','Nelze blíže specifikovat'],
    priznaky:['poruchy chování'],
    prubeh:'Variabilní.', onset:'Dětství.',
    diferencialni_diagnozy:['F98.0','F98.1'], mapovani:{mkn11:null,dsm5:null} },
];

const filtered = nove.filter(n => !existingIds.has(n.id));
console.log(`Část 4: přidáno ${filtered.length} záznamů (F70–F98)`);
module.exports = { nove: filtered };
