const { existingIds } = require('./pridej-diagnozy.cjs');
const fs = require('fs');

const KAT_NEUR = 'F40–F48 Neurotické, stresové a somatoformní poruchy';
const KAT_BEH  = 'F50–F59 Behaviorální syndromy spojené s fyziologickými poruchami';
const KAT_OSOB = 'F60–F69 Poruchy osobnosti a chování u dospělých';

const nove = [

  // ── F40.8, F40.9 ─────────────────────────────────────────────────────────
  { id:'F40.8', kod:'F40.8', nazev_cz:'Jiné fobické úzkostné poruchy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Fobické úzkostné poruchy',
    popis:'Fobické poruchy nesplňující kritéria pro agorafobii, sociální fobii nebo specifické fobie.',
    diagnosticka_kriteria:['Výrazný strach z konkrétního objektu nebo situace','Vyhýbavé chování','Nesplňuje kritéria F40.0, F40.1 nebo F40.2'],
    priznaky:['strach','vyhýbavé chování','anticipační úzkost','vegetativní příznaky'],
    prubeh:'Chronický bez léčby.', onset:'Variabilní.',
    diferencialni_diagnozy:['F40.0','F40.1','F40.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F40.9', kod:'F40.9', nazev_cz:'Fobická úzkostná porucha NS', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Fobické úzkostné poruchy',
    popis:'Neurčená fobická úzkostná porucha.',
    diagnosticka_kriteria:['Fobická úzkost','Bližší specifikace není možná'],
    priznaky:['fobický strach','vyhýbavé chování'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F40.0','F40.1'], mapovani:{mkn11:null,dsm5:null} },

  // ── F41.3, F41.8, F41.9 ─────────────────────────────────────────────────
  { id:'F41.3', kod:'F41.3', nazev_cz:'Smíšená úzkostná a depresivní porucha', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Jiné úzkostné poruchy',
    popis:'Přítomnost jak úzkostných, tak depresivních příznaků, avšak ani jedna složka není natolik výrazná, aby opravňovala samostatnou diagnózu. Velmi časté v primární péči.',
    diagnosticka_kriteria:['Přítomnost úzkosti i deprese','Ani jedna složka nevyhovuje kritériím samostatné diagnózy','Příznaky způsobují klinicky významný distres'],
    priznaky:['úzkost','depresivní nálada','podrážděnost','poruchy spánku','obavy','únava','poruchy soustředění'],
    prubeh:'Chronický nebo epizodický.', onset:'Variabilní, typicky mladá dospělost.',
    diferencialni_diagnozy:['F32','F41.1','F34'], mapovani:{mkn11:'6C71',dsm5:null} },

  { id:'F41.8', kod:'F41.8', nazev_cz:'Jiné určené úzkostné poruchy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Jiné úzkostné poruchy',
    popis:'Úzkostné poruchy nespadající do F41.0–F41.3.',
    diagnosticka_kriteria:['Výrazná úzkost','Nesplňuje kritéria specifičtějších úzkostných poruch'],
    priznaky:['úzkost','somatické příznaky','funkční omezení'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F41.1','F41.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F41.9', kod:'F41.9', nazev_cz:'Úzkostná porucha NS', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Jiné úzkostné poruchy',
    popis:'Neurčená úzkostná porucha.',
    diagnosticka_kriteria:['Klinicky výrazná úzkost','Nelze upřesnit typ'],
    priznaky:['úzkost','vegetativní příznaky'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F41.1','F41.0'], mapovani:{mkn11:null,dsm5:'300.00'} },

  // ── F42.0–F42.9 ──────────────────────────────────────────────────────────
  { id:'F42.0', kod:'F42.0', nazev_cz:'Obsedantně-kompulzivní porucha s převážně obsedantními myšlenkami nebo ruminacemi',
    system:'MKN-10', kategorie:KAT_NEUR, podkategorie:'Obsedantně-kompulzivní porucha',
    popis:'Dominují obsedantní myšlenky, impulsy nebo obrazy (ne primárně nutkavé činy). Myšlenky jsou vtíravé, nežádoucí, způsobují výraznou úzkost. Pacient se jim snaží vzdorovat.',
    diagnosticka_kriteria:['Obsedantní myšlenky, impulsy nebo obrazy jsou dominantní','Pacient je prožívá jako vlastní, ale nepřiměřené','Snahy o odpor nebo neutralizaci','Kompulze nejsou dominantním příznakem'],
    priznaky:['vtíravé myšlenky','obsedantní pochybnosti','ruminace','mentální rituály','strach ze znečištění nebo ublížení','intruzivní obrazy'],
    prubeh:'Chronický, vlnovitý.', onset:'Nejčastěji 10–25 let.',
    diferencialni_diagnozy:['F42.1','F42.2','F41.1','F32'], mapovani:{mkn11:'6B20',dsm5:'300.3'} },

  { id:'F42.1', kod:'F42.1', nazev_cz:'Obsedantně-kompulzivní porucha s převážně nutkavými činy (obsedantní rituály)',
    system:'MKN-10', kategorie:KAT_NEUR, podkategorie:'Obsedantně-kompulzivní porucha',
    popis:'Dominují nutkavé činy (rituály) jako mytí rukou, kontrolování, uspořádávání. Kompulze jsou prováděny ke snížení úzkosti nebo zabránění obávané události, i když nejsou realisticky propojeny s tím, čemu mají zabránit.',
    diagnosticka_kriteria:['Kompulzivní chování je dominantním příznakem','Rituály jsou prováděny ke snížení úzkosti nebo strachu','Pacient ví, že rituály jsou nadměrné nebo iracionální','Zabírají více než 1 hodinu denně nebo výrazně narušují fungování'],
    priznaky:['rituální mytí rukou','kontrolování (zámky, sporák)','uspořádávání předmětů','počítání','opakované činy k dosažení správného pocitu','hoarding'],
    prubeh:'Chronický, vlnovitý.', onset:'Nejčastěji 10–25 let.',
    diferencialni_diagnozy:['F42.0','F42.2','F60.5'], mapovani:{mkn11:'6B20',dsm5:'300.3'} },

  { id:'F42.2', kod:'F42.2', nazev_cz:'Smíšené obsedantní myšlenky a nutkavé činy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Obsedantně-kompulzivní porucha',
    popis:'Nejčastější forma OCD — přibližně v 75 % případů jsou přítomny jak obsedantní myšlenky, tak kompulzivní činy, přičemž žádná složka jednoznačně nepřevládá.',
    diagnosticka_kriteria:['Přítomny jak obsedantní myšlenky, tak kompulzivní činy','Ani jedna složka jednoznačně nepřevládá','Splněna obecná kritéria OCD'],
    priznaky:['vtíravé myšlenky','rituální chování','úzkost při bránění rituálům','funkční omezení','časová náročnost rituálů'],
    prubeh:'Chronický, vlnovitý.', onset:'10–25 let.',
    diferencialni_diagnozy:['F42.0','F42.1','F32','F41.1'], mapovani:{mkn11:'6B20',dsm5:'300.3'} },

  { id:'F42.8', kod:'F42.8', nazev_cz:'Jiné obsedantně-kompulzivní poruchy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Obsedantně-kompulzivní porucha',
    popis:'OCD příznaky nesplňující plně kritéria F42.0–F42.2, nebo atypické formy OCD.',
    diagnosticka_kriteria:['Přítomnost obsedantně-kompulzivních příznaků','Nesplňuje kritéria F42.0–F42.2'],
    priznaky:['obsedantní nebo kompulzivní příznaky','funkční omezení'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F42.2','F42.0'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F42.9', kod:'F42.9', nazev_cz:'Obsedantně-kompulzivní porucha NS', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Obsedantně-kompulzivní porucha',
    popis:'Neurčená obsedantně-kompulzivní porucha.',
    diagnosticka_kriteria:['OCD příznaky','Nelze upřesnit typ'],
    priznaky:['obsedantní myšlenky nebo kompulze'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F42.0','F42.1'], mapovani:{mkn11:null,dsm5:'300.3'} },

  // ── F43 – upřesnění adaptačních poruch F43.2x ────────────────────────────
  { id:'F43.20', kod:'F43.20', nazev_cz:'Porucha přizpůsobení s krátkou depresivní reakcí', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Reakce na těžký stres a poruchy přizpůsobení',
    popis:'Přechodný mírný depresivní stav po identifikovatelné psychosociální zátěži, trvající méně než 1 měsíc.',
    diagnosticka_kriteria:['Identifikovatelná psychosociální zátěž','Depresivní příznaky do 1 měsíce od zátěže','Trvání méně než 1 měsíc','Nesplněna kritéria depresivní epizody'],
    priznaky:['depresivní nálada','pláč','beznaděj','snížená energie'],
    prubeh:'Přechodný, obvykle do 1 měsíce.', onset:'Do 1 měsíce od zátěže.',
    diferencialni_diagnozy:['F32','F43.21','F43.1'], mapovani:{mkn11:'6B43',dsm5:'309.0'} },

  { id:'F43.21', kod:'F43.21', nazev_cz:'Porucha přizpůsobení s prolongovanou depresivní reakcí', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Reakce na těžký stres a poruchy přizpůsobení',
    popis:'Mírný depresivní stav v reakci na prolongovanou stresovou situaci, trvající déle než 1 měsíc, ale méně než 2 roky.',
    diagnosticka_kriteria:['Identifikovatelná psychosociální zátěž trvající déle','Depresivní příznaky','Trvání 1 měsíc–2 roky','Nesplněna kritéria depresivní epizody'],
    priznaky:['prolongovaná depresivní nálada','beznaděj','snížená energie','sociální stažení'],
    prubeh:'Prolongovaný, ale ohraničený.', onset:'Do 1 měsíce od zátěže.',
    diferencialni_diagnozy:['F32','F43.20','F34.1'], mapovani:{mkn11:'6B43',dsm5:'309.1'} },

  { id:'F43.22', kod:'F43.22', nazev_cz:'Porucha přizpůsobení se smíšenou úzkostnou a depresivní reakcí', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Reakce na těžký stres a poruchy přizpůsobení',
    popis:'Nejčastější forma poruchy přizpůsobení — kombinace úzkostných a depresivních příznaků v reakci na identifikovatelnou zátěž.',
    diagnosticka_kriteria:['Identifikovatelná psychosociální zátěž','Smíšené úzkostné a depresivní příznaky','Nesplněna kritéria pro F41.3 nebo F32'],
    priznaky:['úzkost','depresivní nálada','podrážděnost','poruchy spánku','obavy','únava'],
    prubeh:'Přechodný po odeznění zátěže.', onset:'Do 1 měsíce od zátěže.',
    diferencialni_diagnozy:['F41.3','F32','F43.20'], mapovani:{mkn11:'6B43',dsm5:'309.28'} },

  { id:'F43.23', kod:'F43.23', nazev_cz:'Porucha přizpůsobení s převládajícími poruchami jiných emocí', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Reakce na těžký stres a poruchy přizpůsobení',
    popis:'Porucha přizpůsobení s dominantními příznaky jiných emocí než deprese nebo úzkost (u dospělých např. hněv, podrážděnost).',
    diagnosticka_kriteria:['Identifikovatelná zátěž','Dominují jiné emocionální příznaky (hněv, frustrace)','Nesplňuje kritéria jiné poruchy'],
    priznaky:['podrážděnost','hněv','frustrace','emocionální labilita'],
    prubeh:'Přechodný.', onset:'Do 1 měsíce od zátěže.',
    diferencialni_diagnozy:['F43.22','F43.24'], mapovani:{mkn11:'6B43',dsm5:'309.24'} },

  { id:'F43.24', kod:'F43.24', nazev_cz:'Porucha přizpůsobení s převládajícími poruchami chování', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Reakce na těžký stres a poruchy přizpůsobení',
    popis:'Porucha přizpůsobení s dominantními poruchami chování (zejm. u adolescentů), jako je agresivita, antisociální chování, záškoláctví.',
    diagnosticka_kriteria:['Identifikovatelná zátěž','Dominují poruchy chování','Typicky u adolescentů'],
    priznaky:['agresivita','antisociální chování','zneužívání alkoholu','záškoláctví','útěky'],
    prubeh:'Přechodný.', onset:'Do 1 měsíce od zátěže.',
    diferencialni_diagnozy:['F91','F43.22'], mapovani:{mkn11:'6B43',dsm5:'309.3'} },

  { id:'F43.25', kod:'F43.25', nazev_cz:'Porucha přizpůsobení se smíšenou poruchou emocí a chování', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Reakce na těžký stres a poruchy přizpůsobení',
    popis:'Porucha přizpůsobení s kombinací emocionálních příznaků a poruch chování.',
    diagnosticka_kriteria:['Identifikovatelná zátěž','Kombinace emocionálních poruch a poruch chování'],
    priznaky:['deprese','úzkost','poruchy chování','agresivita','sociální problémy'],
    prubeh:'Přechodný.', onset:'Do 1 měsíce od zátěže.',
    diferencialni_diagnozy:['F43.22','F43.24'], mapovani:{mkn11:'6B43',dsm5:'309.4'} },

  { id:'F43.28', kod:'F43.28', nazev_cz:'Porucha přizpůsobení s jinými určenými příznaky', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Reakce na těžký stres a poruchy přizpůsobení',
    popis:'Poruchy přizpůsobení s jinými specifikovanými dominantními příznaky.',
    diagnosticka_kriteria:['Identifikovatelná zátěž','Příznaky nespadají do F43.20–F43.25'],
    priznaky:['variabilní příznaky spojené se zátěží'],
    prubeh:'Přechodný.', onset:'Do 1 měsíce od zátěže.',
    diferencialni_diagnozy:['F43.22','F43.2'], mapovani:{mkn11:'6B43',dsm5:'309.9'} },

  // ── F44 disociativní – chybějící ─────────────────────────────────────────
  { id:'F44.1', kod:'F44.1', nazev_cz:'Disociativní fugue', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Disociativní (konverzní) poruchy',
    popis:'Zdánlivě účelová cesta mimo domov nebo pracoviště spojená se ztrátou paměti na minulost a/nebo převzetím nové identity. Náhlý nástup, obvykle po psychickém traumatu.',
    diagnosticka_kriteria:['Náhlý odchod z domova nebo pracoviště','Amnézie na minulost','Zmatení ohledně osobní identity nebo převzetí nové identity','Není způsobena organicky ani látkami'],
    priznaky:['náhlý odchod bez varování','amnézie na odcestování','zmatenost ohledně identity','nová pseudoidentita','nalezení pacienta daleko od domova'],
    prubeh:'Epizodický, zpravidla krátký. Krizová intervence nutná.', onset:'Akutní, po psychosociálním stresu.',
    diferencialni_diagnozy:['F44.0','F44.8','F60'], mapovani:{mkn11:'6B61',dsm5:'300.13'} },

  { id:'F44.2', kod:'F44.2', nazev_cz:'Disociativní stupor', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Disociativní (konverzní) poruchy',
    popis:'Výrazné snížení nebo absence volních pohybů a normálních reakcí na vnější podněty (světlo, hluk, dotek), bez organické příčiny. Vědomí zachováno.',
    diagnosticka_kriteria:['Výrazná snížení pohybů a reaktivity','Zachování vědomí (reaguje na podněty jinak)','Žádná organická nebo látková příčina','Psychologický stres předchází'],
    priznaky:['nehybnost','mutismus','rigidita','zachované vědomí','absence reakce na podněty','zvláštní výraz ve tváři'],
    prubeh:'Epizodický, akutní.', onset:'Akutní, po psychickém stresu.',
    diferencialni_diagnozy:['F20.2','F44.0','organický stupor'], mapovani:{mkn11:'6B62',dsm5:'300.15'} },

  { id:'F44.4', kod:'F44.4', nazev_cz:'Disociativní pohybové poruchy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Disociativní (konverzní) poruchy',
    popis:'Ztráta nebo omezení schopnosti pohybovat (části) těla, ataxie, třes, paralýza, afonie bez organické příčiny. Klasická konverzní paréza.',
    diagnosticka_kriteria:['Motorický deficit (paréza, paralýza, ataxie, třes, afonie)','Neodpovídá neurologickému vzorci','Psychologická příčina pravděpodobná','Organická porucha vyloučena'],
    priznaky:['paréza nebo paralýza končetin','ataxie','třes','afonie','dystonie','astasie-abasie'],
    prubeh:'Přechodný, může být opakující se.', onset:'Akutní, po stresu.',
    diferencialni_diagnozy:['F44.5','organická paréza','roztroušená skleróza'], mapovani:{mkn11:'6B60',dsm5:'300.11'} },

  { id:'F44.6', kod:'F44.6', nazev_cz:'Disociativní anestezie a senzorická ztráta', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Disociativní (konverzní) poruchy',
    popis:'Ztráta citlivosti kůže nebo smyslových orgánů (zrak, sluch) bez organické příčiny. Výpadky neodpovídají dermatomovému vzorci.',
    diagnosticka_kriteria:['Senzorický deficit (anestezie, hypoestézie, slepota, hluchota)','Neodpovídá organickému vzorci','Psychologická příčina pravděpodobná','Organická porucha vyloučena'],
    priznaky:['ztráta citlivosti neodpovídající dermatomům','rukavicová nebo punčochová anestezie','funkční slepota','funkční hluchota'],
    prubeh:'Přechodný.', onset:'Akutní, po stresu.',
    diferencialni_diagnozy:['F44.4','neurologické poruchy'], mapovani:{mkn11:'6B60',dsm5:'300.11'} },

  { id:'F44.7', kod:'F44.7', nazev_cz:'Smíšené disociativní (konverzní) poruchy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Disociativní (konverzní) poruchy',
    popis:'Kombinace více typů disociativních příznaků (motorické, senzorické, amnestické) v jednom klinickém obrazu.',
    diagnosticka_kriteria:['Přítomny příznaky více typů disociativních poruch','Splněna obecná kritéria disociativní poruchy'],
    priznaky:['amnézie','motorické deficity','senzorická ztráta','stupor','kombinace různých příznaků'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F44.0','F44.4','F44.5'], mapovani:{mkn11:'6B60',dsm5:'300.11'} },

  { id:'F44.8', kod:'F44.8', nazev_cz:'Jiné disociativní (konverzní) poruchy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Disociativní (konverzní) poruchy',
    popis:'Ganserův syndrom, mnohočetná osobnost, psychogenní zmatenost a jiné disociativní stavy nespadající do F44.0–F44.7.',
    diagnosticka_kriteria:['Disociativní příznaky','Nespadají do F44.0–F44.7'],
    priznaky:['Ganserův syndrom (přibližné odpovědi)','psychogenní zmatenost','depersonalizace'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F44.0','F44.1','F48.1'], mapovani:{mkn11:null,dsm5:'300.15'} },

  { id:'F44.9', kod:'F44.9', nazev_cz:'Disociativní (konverzní) porucha NS', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Disociativní (konverzní) poruchy',
    popis:'Neurčená disociativní nebo konverzní porucha.',
    diagnosticka_kriteria:['Disociativní příznaky','Nelze upřesnit typ'],
    priznaky:['disociativní příznaky'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F44.0','F44.4'], mapovani:{mkn11:null,dsm5:'300.15'} },

  // ── F45.8, F45.9 ─────────────────────────────────────────────────────────
  { id:'F45.8', kod:'F45.8', nazev_cz:'Jiné somatoformní poruchy', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Somatoformní poruchy',
    popis:'Somatoformní poruchy nespadající do F45.0–F45.4, jako jsou psychogenní dysfágie, bruxismus, psychogenní pruritus nebo jiné.',
    diagnosticka_kriteria:['Somatické příznaky bez organické příčiny','Nespadají do F45.0–F45.4'],
    priznaky:['psychogenní tělesné příznaky','variabilní somatické stížnosti'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F45.0','F45.1','F45.3'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F45.9', kod:'F45.9', nazev_cz:'Somatoformní porucha NS', system:'MKN-10',
    kategorie:KAT_NEUR, podkategorie:'Somatoformní poruchy',
    popis:'Neurčená somatoformní porucha.',
    diagnosticka_kriteria:['Somatoformní příznaky','Nelze upřesnit typ'],
    priznaky:['somatické příznaky bez organické příčiny'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F45.0','F45.1'], mapovani:{mkn11:null,dsm5:null} },

  // ── F51 – chybějící spánkové poruchy ─────────────────────────────────────
  { id:'F51.1', kod:'F51.1', nazev_cz:'Neorganická hypersomnolence', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Neorganické poruchy spánku',
    popis:'Nadměrná denní ospalost nebo prodloužená noční spánková epizoda bez organické příčiny, v nepřítomnosti narkolepsie.',
    diagnosticka_kriteria:['Nadměrná denní ospalost nebo prodloužený noční spánek','Obtíže s probouzením','Trvání alespoň 1 měsíc','Žádná organická příčina (narkolepsie, apnoe, léky)'],
    priznaky:['nadměrná denní ospalost','prodloužený noční spánek','obtíže s probouzením','automatické chování','kognitivní poruchy'],
    prubeh:'Chronický nebo rekurentní.', onset:'Typicky mladá dospělost.',
    diferencialni_diagnozy:['F51.0','narkolepsie','apnoe','F32'], mapovani:{mkn11:'7B20',dsm5:'307.44'} },

  { id:'F51.2', kod:'F51.2', nazev_cz:'Neorganická porucha spánku a bdění', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Neorganické poruchy spánku',
    popis:'Porucha cirkadiánního rytmu bez organické příčiny — spánek–bdění cyklus je posunut nebo rozvolněn.',
    diagnosticka_kriteria:['Spánek nastupuje nebo končí výrazně mimo požadovanou dobu','Poruchy při pokusech o standardní spánkové hodiny','Žádná organická příčina'],
    priznaky:['posunutý spánkový cyklus','nespavost ve standardní době','ospalost ve dne','sociální nebo pracovní problémy ze spánkového posunu'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F51.0','F51.1','organická cirkadiánní porucha'], mapovani:{mkn11:'7B22',dsm5:'307.45'} },

  { id:'F51.8', kod:'F51.8', nazev_cz:'Jiné neorganické poruchy spánku', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Neorganické poruchy spánku',
    popis:'Jiné parasomnické nebo dyssomnické poruchy bez organické příčiny.',
    diagnosticka_kriteria:['Poruchy spánku','Žádná organická příčina','Nespadají do F51.0–F51.5'],
    priznaky:['variabilní poruchy spánku'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F51.0','F51.3'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F51.9', kod:'F51.9', nazev_cz:'Neorganická porucha spánku NS', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Neorganické poruchy spánku',
    popis:'Neurčená neorganická porucha spánku.',
    diagnosticka_kriteria:['Porucha spánku','Žádná organická příčina','Nelze upřesnit typ'],
    priznaky:['poruchy spánku'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F51.0','F51.1'], mapovani:{mkn11:null,dsm5:'307.40'} },

  // ── F52 sexuální dysfunkce ────────────────────────────────────────────────
  { id:'F52.1', kod:'F52.1', nazev_cz:'Sexuální averze a nedostatek sexuálního potěšení', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'Buď prospect sexu vyvolává silný negativní afekt (averze) nebo sexuální akty neprovázeny potěšením (anedonická sexualita), přestože probíhají normálně.',
    diagnosticka_kriteria:['Přetrvávající nebo opakující se averze vůči sexu nebo absence potěšení ze sexuální aktivity','Stav způsobuje distres nebo meziosobní problémy','Není způsoben jinou poruchou nebo substancí'],
    priznaky:['odpor vůči sexu','vyhýbavé chování','absence sexuálního potěšení','úzkost při sexuálních podnětech'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F52.0','F52.2','F60'], mapovani:{mkn11:'HA20',dsm5:'302.71'} },

  { id:'F52.2', kod:'F52.2', nazev_cz:'Selhání genitální odpovědi', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'U mužů: erektilní dysfunkce (neschopnost dosáhnout nebo udržet erekci). U žen: selhání lubrikační odpovědi.',
    diagnosticka_kriteria:['U muže: přetrvávající nebo opakující se neschopnost dosáhnout/udržet errekci','U ženy: přetrvávající nedostatečná lubrikace','Žádná organická příčina dominuje','Způsobuje distres'],
    priznaky:['erektilní dysfunkce (muži)','nedostatečná lubrikace (ženy)','úzkost z výkonu','vyhýbání se sexuálním aktivitám'],
    prubeh:'Chronický nebo situační.', onset:'Variabilní.',
    diferencialni_diagnozy:['F52.0','organická erektilní dysfunkce','F52.3'], mapovani:{mkn11:'HA20',dsm5:'302.72'} },

  { id:'F52.3', kod:'F52.3', nazev_cz:'Orgasmická dysfunkce', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'Přetrvávající nebo opakující se zpomalení, absence nebo předčasnost orgasmu.',
    diagnosticka_kriteria:['Přetrvávající porucha orgasmu (absence, zpožení nebo předčasnost)','Žádná organická příčina dominuje','Způsobuje distres'],
    priznaky:['absence orgasmu','zpožděný orgasmus','předčasná ejakulace (muži)','distres ze sexuální aktivity'],
    prubeh:'Chronický nebo situační.', onset:'Variabilní.',
    diferencialni_diagnozy:['F52.2','F52.4','organická příčina'], mapovani:{mkn11:'HA20',dsm5:'302.73'} },

  { id:'F52.5', kod:'F52.5', nazev_cz:'Neorganický vaginismus', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'Mimovolní spasmus svalů pochvy při pokusu o penetraci, znemožňující nebo ztěžující pohlavní styk. Bez organické příčiny.',
    diagnosticka_kriteria:['Mimovolní spasmus vaginálního svalstva při pokusu o penetraci','Znemožňuje nebo znesnadňuje pohlavní styk','Žádná organická příčina'],
    priznaky:['mimovolní spasmus pochvy','nemožnost penetrace','strach z bolesti','vyhýbání se sexu'],
    prubeh:'Chronický.', onset:'Variabilní, často od prvního pokusu o koitus.',
    diferencialni_diagnozy:['organický vaginismus','F52.6','F52.1'], mapovani:{mkn11:'HA20',dsm5:'306.51'} },

  { id:'F52.6', kod:'F52.6', nazev_cz:'Neorganická dyspareunie', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'Bolest při pohlavním styku bez organické příčiny. Může se vyskytovat u mužů i žen.',
    diagnosticka_kriteria:['Bolest při pohlavním styku','Žádná organická příčina dostatečně nevysvětluje intenzitu bolesti','Způsobuje distres'],
    priznaky:['bolest při koitu','vyhýbání se sexu','strach','emocionální distres'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F52.5','organická dyspareunie'], mapovani:{mkn11:'HA20',dsm5:'302.76'} },

  { id:'F52.7', kod:'F52.7', nazev_cz:'Nadměrná sexuální apetence', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'Výrazně zvýšená sexuální touha způsobující distres nebo interpersonální problémy.',
    diagnosticka_kriteria:['Výrazně zvýšená sexuální touha','Způsobuje distres nebo problémy ve vztazích','Žádná organická nebo maniakální příčina'],
    priznaky:['nadměrná sexuální touha','nutkavé sexuální chování','interpersonální problémy','distres'],
    prubeh:'Chronický nebo epizodický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F30.1','F65','organická hypersexualita'], mapovani:{mkn11:'HA20',dsm5:null} },

  { id:'F52.8', kod:'F52.8', nazev_cz:'Jiné sexuální dysfunkce', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'Sexuální dysfunkce nespadající do F52.0–F52.7.',
    diagnosticka_kriteria:['Sexuální dysfunkce','Nespadá do F52.0–F52.7'],
    priznaky:['variabilní sexuální problémy'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F52.0','F52.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F52.9', kod:'F52.9', nazev_cz:'Sexuální dysfunkce NS', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Sexuální dysfunkce',
    popis:'Neurčená sexuální dysfunkce.',
    diagnosticka_kriteria:['Sexuální dysfunkce','Nelze upřesnit typ'],
    priznaky:['sexuální dysfunkce'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F52.0','F52.2'], mapovani:{mkn11:null,dsm5:'302.70'} },

  // ── F55 zneužívání látek bez závislosti ──────────────────────────────────
  { id:'F55.0', kod:'F55.0', nazev_cz:'Zneužívání antidepresiv', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Opakované a škodlivé užívání antidepresiv bez lékařského doporučení nebo nad doporučenou dávku.',
    diagnosticka_kriteria:['Pravidelné užívání antidepresiv','Bez lékařské indikace nebo nad doporučenou dávku','Průkaz škodlivých fyzických nebo psychických následků'],
    priznaky:['serotoninový syndrom','kardiotoxicita při předávkování','závislostní chování'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F32','F34.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.1', kod:'F55.1', nazev_cz:'Zneužívání laxativ', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Opakované nadměrné užívání laxativ mimo léčebnou indikaci, často asociované s poruchami příjmu potravy.',
    diagnosticka_kriteria:['Pravidelné nadměrné užívání laxativ','Průkaz fyzického poškození (elektrolytová dysbalance)','Bez závislosti v pravém slova smyslu'],
    priznaky:['průjem', 'elektrolytová dysbalance','slabost','říhání','poškození střeva'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F50.2','F50.0'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.2', kod:'F55.2', nazev_cz:'Zneužívání analgetik', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Nadměrné užívání analgetik (aspirinu, paracetamolu, NSAID) mimo léčebnou indikaci nebo nad doporučenou dávku.',
    diagnosticka_kriteria:['Pravidelné nadměrné užívání analgetik','Průkaz fyzického poškození (hepatotoxicita, nefrotoxicita, GI poškození)'],
    priznaky:['GI příznaky','hepatotoxicita','nefrotoxicita','bolest hlavy z vysazení'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F11.1','F45.4'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.3', kod:'F55.3', nazev_cz:'Zneužívání antacid', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Nadměrné a škodlivé užívání antacid.',
    diagnosticka_kriteria:['Nadměrné užívání antacid','Průkaz fyzického poškození (metabolická alkalóza, poruchy elektrolytů)'],
    priznaky:['metabolická alkalóza','hypofosfatémie','průjem'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F55.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.4', kod:'F55.4', nazev_cz:'Zneužívání vitamínů', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Nadměrné užívání vitamínů způsobující hypervitaminózu.',
    diagnosticka_kriteria:['Nadměrné užívání vitamínů','Průkaz fyzického poškození (hypervitaminóza A, D, B6)'],
    priznaky:['hypervitaminóza','hepatotoxicita','neuropatie (B6)'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F55.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.5', kod:'F55.5', nazev_cz:'Zneužívání steroidů a hormonů', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Nadměrné užívání anabolických steroidů nebo jiných hormonů mimo léčebnou indikaci (doping).',
    diagnosticka_kriteria:['Nadměrné užívání steroidů/hormonů','Průkaz fyzického nebo psychického poškození','Bez závislosti v pravém smyslu'],
    priznaky:['agresivita','akné','hepatotoxicita','kardiovaskulární komplikace','poruchy nálady'],
    prubeh:'Chronický.', onset:'Typicky adolescenti a mladí dospělí.',
    diferencialni_diagnozy:['F55.2','F30.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.6', kod:'F55.6', nazev_cz:'Zneužívání rostlinných nebo lidových léků', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Nadměrné nebo škodlivé užívání bylinkových přípravků nebo tradičních léků.',
    diagnosticka_kriteria:['Pravidelné nadměrné užívání','Průkaz fyzického poškození'],
    priznaky:['hepatotoxicita','interakce s léky','variabilní příznaky'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F55.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.8', kod:'F55.8', nazev_cz:'Zneužívání jiných látek', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Zneužívání jiných látek nezpůsobujících závislost, jako jsou projímadla, léky na hubnutí nebo jiné.',
    diagnosticka_kriteria:['Pravidelné nadměrné užívání','Průkaz fyzického poškození','Žádná závislost'],
    priznaky:['variabilní dle látky'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F55.1','F55.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F55.9', kod:'F55.9', nazev_cz:'Zneužívání NS látky', system:'MKN-10',
    kategorie:KAT_BEH, podkategorie:'Zneužívání látek bez závislosti',
    popis:'Neurčené zneužívání látky nezpůsobující závislost.',
    diagnosticka_kriteria:['Zneužívání látky','Nelze upřesnit typ'],
    priznaky:['variabilní'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F55.0','F55.2'], mapovani:{mkn11:null,dsm5:null} },

  // ── F62, F63, F64, F65, F66 ──────────────────────────────────────────────
  { id:'F62.1', kod:'F62.1', nazev_cz:'Trvalá změna osobnosti po psychiatrickém onemocnění', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Trvalé změny osobnosti',
    popis:'Trvalá, nevratná změna osobnostního vzorce po těžkém psychiatrickém onemocnění (zejm. psychóze). Není přímým projevem psychózy.',
    diagnosticka_kriteria:['Trvalá změna osobnostního vzorce po těžkém psychiatrickém onemocnění','Přímý projev nemoci je vyloučen','Změna přetrvává po ukončení akutní fáze','Před onemocněním jiné rysy osobnosti'],
    priznaky:['závislost a chronická role nemocného','nevíra v uzdravení','sociální stažení','pasivita','ztráta iniciativy'],
    prubeh:'Trvalý.', onset:'Po těžkém psychiatrickém onemocnění.',
    diferencialni_diagnozy:['F62.0','F60','reziduální schizofrenie'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F62.8', kod:'F62.8', nazev_cz:'Jiné trvalé změny osobnosti', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Trvalé změny osobnosti',
    popis:'Jiné trvalé změny osobnosti nespadající pod F62.0 nebo F62.1.',
    diagnosticka_kriteria:['Trvalá změna osobnosti','Identifikovatelná příčina','Nespadá do F62.0 nebo F62.1'],
    priznaky:['trvalé změny osobnostního vzorce'],
    prubeh:'Trvalý.', onset:'Po identifikovatelné příčině.',
    diferencialni_diagnozy:['F62.0','F62.1','F60'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F62.9', kod:'F62.9', nazev_cz:'Trvalá změna osobnosti NS', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Trvalé změny osobnosti',
    popis:'Neurčená trvalá změna osobnosti.',
    diagnosticka_kriteria:['Trvalá změna osobnosti','Nelze upřesnit příčinu nebo typ'],
    priznaky:['změna osobnostního vzorce'],
    prubeh:'Trvalý.', onset:'Variabilní.',
    diferencialni_diagnozy:['F62.0','F62.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F63.3', kod:'F63.3', nazev_cz:'Trichotilomanie', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy návyků a impulzů',
    popis:'Opakované vytrhávání vlastních vlasů způsobující patrnou alopecii, s naléhavostí před činem a úlevou po něm.',
    diagnosticka_kriteria:['Opakované vytrhávání vlasů vedoucí k alopecii','Naléhavost nebo napětí bezprostředně před činem','Úleva nebo potěšení po činu','Porucha způsobuje distres nebo omezení funkcí'],
    priznaky:['vytrhávání vlasů','alopecia areata nebo difuzní','naléhavost','úleva po činu','přítomnost rituálů (zkoumání vlasů, žvýkání)'],
    prubeh:'Chronický, vlnovitý.', onset:'Dětství nebo adolescence.',
    diferencialni_diagnozy:['F42','F98.4','organická alopecie'], mapovani:{mkn11:'6B25',dsm5:'312.39'} },

  { id:'F63.8', kod:'F63.8', nazev_cz:'Jiné poruchy návyků a impulzů', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy návyků a impulzů',
    popis:'Jiné poruchy návyků a impulzů nespadající do F63.0–F63.3 (např. nutkavé nakupování, sebezraňování).',
    diagnosticka_kriteria:['Opakované impulzivní chování','Napětí před činem a úleva po něm','Způsobuje distres nebo omezení funkcí'],
    priznaky:['impulzivní chování','ztráta kontroly','úleva po činu','opakující se vzorec'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F63.0','F63.3','F60'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F63.9', kod:'F63.9', nazev_cz:'Porucha návyků a impulzů NS', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy návyků a impulzů',
    popis:'Neurčená porucha návyků a impulzů.',
    diagnosticka_kriteria:['Impulzivní chování','Nelze upřesnit typ'],
    priznaky:['impulzivní chování','ztráta kontroly'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F63.0','F63.8'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F64.1', kod:'F64.1', nazev_cz:'Duální-rolový transvestitismus', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy pohlavní identity',
    popis:'Nošení oblečení opačného pohlaví za účelem prožívání příslušnosti k opačnému pohlaví, bez sexuálního vzrušení a bez touhy po trvalé změně pohlaví.',
    diagnosticka_kriteria:['Nošení oblečení opačného pohlaví','Bez sexuálního vzrušení','Bez trvalé touhy po změně pohlaví','Prožitek příslušnosti k jinému pohlaví je přechodný'],
    priznaky:['cross-dressing','prožívání opačného pohlaví','bez sexuálního vzrušení','bez trvalé dysforie'],
    prubeh:'Chronický nebo epizodický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F64.0','F65.1'], mapovani:{mkn11:'HA60',dsm5:null} },

  { id:'F64.2', kod:'F64.2', nazev_cz:'Porucha pohlavní identity v dětství', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy pohlavní identity',
    popis:'Přetrvávající, výrazná nespokojenost s vlastním pohlavím a identifikace s opačným pohlavím, projevující se v dětství (před pubertou).',
    diagnosticka_kriteria:['Trvalá intenzivní nespokojenost s biologickým pohlavím','Silná identifikace s opačným pohlavím','Projevuje se v dětství, před pubertou','Způsobuje distres nebo funkční omezení'],
    priznaky:['odmítání vlastního pohlaví','identifikace s opačným pohlavím','preference oblečení a her opačného pohlaví','distres'],
    prubeh:'Může přetrvat do dospělosti (tranzice na F64.0) nebo odeznít.', onset:'Dětství.',
    diferencialni_diagnozy:['F64.0','normální genderová variabilita'], mapovani:{mkn11:'HA61',dsm5:'302.6'} },

  { id:'F64.8', kod:'F64.8', nazev_cz:'Jiné poruchy pohlavní identity', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy pohlavní identity',
    popis:'Jiné poruchy pohlavní identity nespadající do F64.0–F64.2.',
    diagnosticka_kriteria:['Porucha pohlavní identity','Nespadá do F64.0–F64.2'],
    priznaky:['pohlavní dysforie','variabilní klinický obraz'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F64.0','F64.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F64.9', kod:'F64.9', nazev_cz:'Porucha pohlavní identity NS', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy pohlavní identity',
    popis:'Neurčená porucha pohlavní identity.',
    diagnosticka_kriteria:['Pohlavní dysforie','Nelze upřesnit typ'],
    priznaky:['pohlavní dysforie'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F64.0'], mapovani:{mkn11:null,dsm5:'302.85'} },

  { id:'F65.1', kod:'F65.1', nazev_cz:'Fetišistický transvestitismus', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy sexuální preference',
    popis:'Nošení oblečení opačného pohlaví za účelem sexuálního vzrušení, odlišuje se od duálního transvestitismu přítomností sexuální komponenty.',
    diagnosticka_kriteria:['Nošení oblečení opačného pohlaví','Sexuální vzrušení je součástí','Touha odložit oblečení po orgasmu','Odlišné od F64.1 přítomností sexuální komponenty'],
    priznaky:['cross-dressing se sexuálním vzrušením','pocity viny','sociální skrývání'],
    prubeh:'Chronický.', onset:'Adolescence.',
    diferencialni_diagnozy:['F65.0','F64.1'], mapovani:{mkn11:'6D32',dsm5:'302.3'} },

  { id:'F65.2', kod:'F65.2', nazev_cz:'Exhibicionismus', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy sexuální preference',
    popis:'Opakující se nebo trvalá tendence odhalovat genitálie cizím osobám (obvykle opačného pohlaví) na veřejnosti bez nabídky dalšího kontaktu.',
    diagnosticka_kriteria:['Opakované odhalování genitálií cizím osobám','Bez nabídky dalšího kontaktu','Sexuální vzrušení je součástí','Způsobuje distres nebo právní problémy'],
    priznaky:['odhalování genitálií','sexuální vzrušení z reakce oběti','opakující se nutkání','pocity viny','právní problémy'],
    prubeh:'Chronický.', onset:'Typicky 15–25 let, téměř výhradně muži.',
    diferencialni_diagnozy:['F65.3','F65.0','F60'], mapovani:{mkn11:'6D32',dsm5:'302.4'} },

  { id:'F65.3', kod:'F65.3', nazev_cz:'Voyeurismus', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy sexuální preference',
    popis:'Opakující se tendence pozorovat lidi při intimních aktivitách (svlékání, sexu) bez jejich vědomí.',
    diagnosticka_kriteria:['Opakované pozorování cizích osob při intimních aktivitách','Bez jejich vědomí a souhlasu','Sexuální vzrušení je součástí','Způsobuje distres nebo právní problémy'],
    priznaky:['nutkavé sledování','sexuální vzrušení z pozorování','sociální izolace','právní problémy'],
    prubeh:'Chronický.', onset:'Adolescence nebo mladá dospělost.',
    diferencialni_diagnozy:['F65.2','F65.0'], mapovani:{mkn11:'6D32',dsm5:'302.82'} },

  { id:'F65.5', kod:'F65.5', nazev_cz:'Sadomasochismus', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy sexuální preference',
    popis:'Preference sexuální aktivity zahrnující způsobování nebo přijímání bolesti, ponížení nebo omezování jako podmínka pro sexuální uspokojení.',
    diagnosticka_kriteria:['Preference bolesti, ponížení nebo omezování při sexu','Jako zdroj nebo příjemce těchto aktivit','Způsobuje distres nebo způsobuje poškození'],
    priznaky:['sexuální vzrušení z bolesti nebo ponížení','ritualizované sexuální chování','může zahrnovat nebezpečné praktiky'],
    prubeh:'Chronický.', onset:'Adolescence nebo mladá dospělost.',
    diferencialni_diagnozy:['F65.0','F65.2','konsensuální BDSM'], mapovani:{mkn11:'6D32',dsm5:'302.84'} },

  { id:'F65.6', kod:'F65.6', nazev_cz:'Mnohočetné poruchy sexuální preference', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy sexuální preference',
    popis:'Kombinace více různých poruch sexuální preference u téhož jedince.',
    diagnosticka_kriteria:['Splnění kritérií pro více typů parafílií','Způsobují distres nebo škodu'],
    priznaky:['kombinace více parafílií','výrazné funkční omezení'],
    prubeh:'Chronický.', onset:'Adolescence.',
    diferencialni_diagnozy:['F65.0','F65.1','F65.2'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F65.8', kod:'F65.8', nazev_cz:'Jiné poruchy sexuální preference', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy sexuální preference',
    popis:'Jiné parafílie nespadající do F65.0–F65.6, jako jsou frotteurismus, nekrofílie, urolalie aj.',
    diagnosticka_kriteria:['Sexuální preference nespadající do F65.0–F65.6','Způsobují distres nebo poškození'],
    priznaky:['atypická sexuální preference','nutkavost','funkční omezení'],
    prubeh:'Chronický.', onset:'Variabilní.',
    diferencialni_diagnozy:['F65.0','F65.2'], mapovani:{mkn11:'6D32',dsm5:null} },

  { id:'F65.9', kod:'F65.9', nazev_cz:'Porucha sexuální preference NS', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Poruchy sexuální preference',
    popis:'Neurčená porucha sexuální preference.',
    diagnosticka_kriteria:['Porucha sexuální preference','Nelze upřesnit typ'],
    priznaky:['atypická sexuální preference'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F65.0','F65.2'], mapovani:{mkn11:null,dsm5:'302.9'} },

  { id:'F66.0', kod:'F66.0', nazev_cz:'Porucha sexuálního zrání', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Psychologické a behaviorální poruchy spojené se sexuálním vývojem',
    popis:'Nejistota ohledně pohlavní identity nebo sexuální orientace způsobující úzkost nebo depresi. Týká se zejm. adolescentů.',
    diagnosticka_kriteria:['Nejistota ohledně pohlavní identity nebo sexuální orientace','Způsobuje úzkost nebo depresi','Trvá déle než přechodné pochybnosti v adolescenci'],
    priznaky:['nejistota ohledně pohlavní identity','úzkost','depresivní nálada','problémy se sebevnímáním'],
    prubeh:'Přechodný nebo přetrvávající.', onset:'Adolescence.',
    diferencialni_diagnozy:['F64.0','F66.1','F32'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F66.1', kod:'F66.1', nazev_cz:'Egodystonická sexuální orientace', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Psychologické a behaviorální poruchy spojené se sexuálním vývojem',
    popis:'Pohlavní identita nebo sexuální orientace (hetero-, homo- nebo bisexuální) je jasná, ale pacient si přeje, aby byla jiná, a vyhledává pomoc ke změně.',
    diagnosticka_kriteria:['Jasná pohlavní identita nebo sexuální orientace','Přání jiné orientace z důvodu psychických nebo sociálních potíží','Způsobuje distres'],
    priznaky:['distres ohledně sexuální orientace','přání změny orientace','úzkost','depresivní nálada'],
    prubeh:'Variabilní, závisí na sociálních faktorech.', onset:'Adolescence nebo dospělost.',
    diferencialni_diagnozy:['F66.0','F32','F64.0'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F66.2', kod:'F66.2', nazev_cz:'Porucha sexuálního vztahu', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Psychologické a behaviorální poruchy spojené se sexuálním vývojem',
    popis:'Pohlavní identita nebo sexuální orientace způsobuje obtíže v navazování nebo udržování sexuálních vztahů.',
    diagnosticka_kriteria:['Pohlavní identita nebo orientace způsobuje vztahové obtíže','Způsobuje distres'],
    priznaky:['obtíže ve vztazích','sociální izolace','distres ze sexuální identity'],
    prubeh:'Variabilní.', onset:'Adolescence nebo dospělost.',
    diferencialni_diagnozy:['F66.0','F66.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F66.8', kod:'F66.8', nazev_cz:'Jiné psychosexuální vývojové poruchy', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Psychologické a behaviorální poruchy spojené se sexuálním vývojem',
    popis:'Jiné psychologické poruchy spojené se sexuálním vývojem.',
    diagnosticka_kriteria:['Psychologické problémy spojené se sexuálním vývojem','Nespadají do F66.0–F66.2'],
    priznaky:['problémy se sexuálním vývojem'],
    prubeh:'Variabilní.', onset:'Adolescence.',
    diferencialni_diagnozy:['F66.0','F66.1'], mapovani:{mkn11:null,dsm5:null} },

  { id:'F66.9', kod:'F66.9', nazev_cz:'Psychosexuální vývojová porucha NS', system:'MKN-10',
    kategorie:KAT_OSOB, podkategorie:'Psychologické a behaviorální poruchy spojené se sexuálním vývojem',
    popis:'Neurčená psychologická porucha spojená se sexuálním vývojem.',
    diagnosticka_kriteria:['Psychologický distres spojený se sexuálním vývojem','Nelze upřesnit typ'],
    priznaky:['distres ze sexuálního vývoje'],
    prubeh:'Variabilní.', onset:'Variabilní.',
    diferencialni_diagnozy:['F66.0'], mapovani:{mkn11:null,dsm5:null} },
];

const filtered = nove.filter(n => !existingIds.has(n.id));
console.log(`Část 3: přidáno ${filtered.length} záznamů (F40-F66)`);
module.exports = { nove: filtered };
